[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ireranker"
version = "0.0.1"
description = "Este repo implementa distintos algoritmos de Information Retrieval para la parte de rerank en RAG."
authors = [
  { name = "Jerem\u00edas Figueiredo Paschmann, Juan Kaplan, Francisco Nattero, Santiago Mauricio Barron Bucolo" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "loguru",
    "numpy",
    "pandas",
    "python-dotenv",
    "scipy",
    "tqdm",
    "typer",
]
requires-python = "~=3.10.0"

 [project.scripts]


[project.optional-dependencies]
tests = ["pytest"]
lint = ["ruff==0.6.4"]
beir = ["beir", "pyserini"]
notebooks = ["ipython", "jupyterlab", "matplotlib", "notebook", "seaborn"]
dev = [
    "pytest",
    "ruff==0.6.4",
    "ipython",
    "jupyterlab",
    "matplotlib",
    "notebook",
    "seaborn",
]

[tool.ruff]
line-length = 99
src = ["ireranker"]
include = ["pyproject.toml", "ireranker/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ireranker"]
force-sort-within-sections = true
